### PR TITLE
Added Bound.TH

### PR DESCRIPTION
**Pull request by Icelandjack**
As discussed, Template Haskell for deriving Applicative/Monad instances, Eq and Ord are problematic but may be generated as well, discussed in comments. This allows writing:

```haskell
data Exp a = V a | App (Exp a) (Exp a) | Lam (Scope () Exp a)
  deriving (Show, Functor)

instance Show1 Exp
instance Eq1 Exp
deriving instance Eq a => Eq (Exp a)
instance Ord1 Exp
deriving instance Ord a => Ord (Exp a) 
makeBound ''Exp
```

This is a start, it doesn't work on differently kinded types nor does it deal with lists or Functors so

```haskell
data Exp a = ... 
  | Let {-# UNPACK #-} !Int [Scope Int Exp a] (Scope Int Exp a)
  | Case (Exp a) [Alt Exp a]
```

won't fly.

`makeBound` may be a poor name since I might add a quotation that derive instance of the `Bound` class

### CODE REVIEW

**Comment by ekmett** [comment]
This currently breaks 7.4 and 7.6 support at the very least. I can't easily test older versions right now.

**Comment by Icelandjack** [comment]
Same here, any ideas? The Applicative/Monad constructors seem to be applied to type variables

**Comment by Icelandjack** [comment]
A few thoughts, it's possible to derive `Eq` and `Ord` in the actual data declaration using `DeriveAnyClass`

> ...
> import Prelude.Extras
> 
> data Exp a = V a | App (Exp a) (Exp a) | Lam (Scope () Exp a)
>   deriving (Eq, Eq1,
>             Ord, Ord1,
>             Show, Show1,
>             Functor, Traversable, Foldable)
> 
> makeBound ''Exp

which limits it to 7.10. For older compilers I haven't found a way to derive `Eq` and `Ord` instances without `StandaloneDeriving` because of the `Monad` constraint, someone more creative can pitch in.

When writing one-off types I'd like to avoid going through the motions importing `Prelude.Extras` and deriving the higher-order instances, if there are no objections I'll implement `deriveAll`

> ...
> 
> data Exp a = V a | App (Exp a) (Exp a) | Lam (Scope () Exp a) 
>   deriving (Functor, Traversable, Foldable)
> 
> deriveAll ''Exp [''Eq, ''Ord, ''Show]

with the same meaning as above.

**Comment by ekmett** [comment]
Eventually we'll be dropping `Prelude.Extras` in favor of `Data.Functor.Classes`.

If my current proposal to move `Data.Functor.Classes` into `base` goes through then `DeriveAnyClass` can continue to work on `Eq1` if I add `DefaultSignatures` to it to let it work like the current version.

-Edward

**Comment by Icelandjack** [comment]
Seems to be working

**Pull request merged**
