### PR TITLE
run the doctests from the Imperative example

### PR DESCRIPTION
**Pull request by gelisam**
the other examples have doctests as well, but they are currently
failing, mostly due to the lack of Show instances.

### CODE REVIEW

**Comment by cartazio** [comment]
... It's worth noting that any any infix constructor has a quadratic or
worse blow up wrt the associated read instance. ... So make sure this
doesn't then tigger that ;)

**Comment by gelisam** [comment]
There is no call to `read` in this pull request nor in `Imperative. hs`... was your comment perhaps meant for a different pull request?

**Comment by cartazio** [comment]
More like me wondering if doc tests do a string based compare or if they
invoke read.  I guess they probably do a string compare?

Pay me no mind :)

**Comment by gelisam** [comment]
Ah, I see! Don't worry, it's a string-based comparison against whatever ghci outputs when you type in the test expression. So by duplicating ghci's error messages in case of a type error or an exception, you can also make sure that a particular invalid expression doesn't type check or that another expression fails at runtime.

**Comment by phadej** [comment]
Could you remove the `!impl(ghc >= 7.10)` check for `test-suite Imperative`? So it's built (it probably will fail sooner than thru doctest if there is some compilation errors)

**Comment by gelisam** [comment]
Here you go!

**Comment by phadej** [comment]
Great, thanks

**Pull request merged**
