### PR TITLE
how to use bound with imperative languages

### PR DESCRIPTION
**Pull request by gelisam**
Here is the PR you asked for two years ago. Better late than never :)

### CODE REVIEW

**Comment by cartazio** [comment]
This looks like a small instance of let normal form / anf / ssa! Which is
awesome !
I'm not sure if it actually can be deemed "imperative " except in exactly
the same sense that monads are imperative :)

**Comment by phadej** [comment]
You probably should add new example to `extra-source-files` in cabal, or/and add it as a test-suite, so it's build on Travis

**Comment by gelisam** [comment]
> I'm not sure if it actually can be deemed "imperative " except in exactly
the same sense that monads are imperative :)

Still not imperative enough? Like I said in the [Reddit discussion](https://www.reddit.com/r/haskell/comments/4ni4ni/modeling_imperative_language_using_bound/d4453sv) which sparked this pull request, I didn't submit my [original example](https://gist.github.com/gelisam/9561388) two years ago because Kmett said it would be good for bound to have an example of an imperative language, but after taking a closer look at my example, I decided it was not imperative enough. The reason I didn't consider it imperative enough is because I used a single global anonymous variable, like we do in the State monad. Regular imperative languages never do that, they use named mutable variables, and so I didn't think it would be a very good example of using bound to implement the mutable variables of an imperative language.

Do you have a more imperative example in mind? I could easily replace the `swp` instruction by an assignment instruction, would that help?

**Comment by gelisam** [comment]
> You probably should add new example to extra-source-files in cabal, or/and add it as a test-suite, so it's build on Travis

Okay, but it looks like your Travis suite is already broken! The error says `cabal-1.22: You need to re-run the 'configure' command. The version of Cabal being used has changed (was Cabal-1.22.4.0, now Cabal-1.22.5.0)`, which doesn't sound like an error which was introduced by my changes, especially since I haven't added my file to `extra-source-files` yet. I guess I should wait until somebody on your team fixes this, and then I should rebase on top of that fix, and then I should add my file to `extra-source-files`?

**Comment by phadej** [comment]
I'll check what's wrong with that job, it's unrelated to your changes indeed

**Pull request merged**
