### PR TITLE
Add more generic instances

### PR DESCRIPTION
**Pull request by treeowl**
Add `Generic` and `Generic1` instances for `Scope`. Add `Generic1`
instances for `Var` and `Name`.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Generally looks good.

One thing I'll request is that you don't guard the `Generic` instances with `#if __GLASGOW_HASKELL__ >= 704 ... #endif`, since GHC 7.4 is the earliest version that `bound` supports. Also, there are still some lingering `#if __GLASGOW_HASKELL__ >= 704 ... #endif` blocks still floating around from back before we stopped supporting GHCs earlier than 7.4—can you remove these as well? Thanks!

**Comment by ekmett** [comment]
No objection here, modulo Ryan's caveats.

**Comment by treeowl** [comment]
I took the liberty of redefining the `NFData` instances by hand. There's no particularly good reason to lean on generics when they're so simple. The CPP to make sure `DefaultSignatures` were available and that the defaults were the right ones took up about as much space as hand-written instances.

**Comment by treeowl** [comment]
@RyanGlScott, do you think it's fine now? The Travis failures are unfortunate, but also clearly not my fault; someone who knows more about Travis will have to figure those out.

**Comment by RyanGlScott** [comment]
Thanks!

**Pull request merged**
